### PR TITLE
Allow the installation of filer.js with npm

### PR DESCRIPTION
**Pull request by bumxu**
Hello,

I opt for allowing the installation of **filer.js** with **npm**.
This adds an standard `package.json` definition with the minimum required information according e840348b6f156f47c6261b0b10ead8488820c541, and a `.npmignore` file for the lighter possible installation.

This is only a suggestion for future use, I can always use my own fork, thanks for this excellent wrapper.

### CODE REVIEW

**Comment by ebidel** [comment]
👍

**Comment by vitalets** [comment]
Hi,

did you published it to npm? 
I don't see `filer.js` there: https://www.npmjs.com/package/filer.js

**Comment by ebidel** [comment]
Never published it to the registry, but I think you can do `npm install  ebidel/filer.js`

**Comment by vitalets** [comment]
> Never published it to the registry

why not?)

**Comment by ebidel** [comment]
done! https://www.npmjs.com/package/filer.js

**Comment by vitalets** [comment]
thank you! 👍

**Pull request merged**
